### PR TITLE
Added support for secretReference to connect to external database

### PR DESCRIPTION
**Pull request by dbt-lucka**
Made it possible to reference an existing secret for specifying full DSN, as an alternative to the constructed DSN with cleartext password.

### CODE REVIEW

**Comment by robjuz** [comment]
Hi. Thx for the PR. It looks good. I just need to check if the database credentials are used somewhere else.

**Comment by dbt-lucka** [comment]
Cool. Just tested it on my GCP Cluster and it works. I forgot to document in values.yaml though. Will do so tomorrow.

**Comment by dbt-lucka** [comment]
Updated the documentation of values.yaml.

**Comment by dbt-lucka** [comment]
Nominatim is now up and running with the DSN injected as a secret 👍 

Deployment:
image

Secret:
image

**Comment by dbt-lucka** [comment]
Creating a new PR that incorporates this feature and #38 as well.

**Pull request closed without merging**
