### PR TITLE
Added Hostname Option to be an IP Address

### PR DESCRIPTION
**Pull request by BackInBash**
Option to allow an Reverse Proxy in front of Kimai

### CODE REVIEW

**Comment by BackInBash** [comment]
In front of an K8s LoadBalancer you need to set the TRUSTED_HOST Variable. But the LoadBalancer sets the Proxy Headers so the Location Header ist the IP address of the LoadBalancer itself.

So in order to get around this you need to set the TRUSTED_HOST var to the IP Address of the LoadBalancer.
The Hostname attribute is type safe so you can't put an IP in there.
That's why this change is necessary.

https://github.com/symfony/symfony/issues/29609

**Comment by robjuz** [comment]
If I understand this correctly you are using `service.type = LoadBalancer` yes?
I thing that the `service.loadBalancerIP` is a better candidate for the TRUSTED_HOST

**Comment by BackInBash** [comment]
I've tried it but sadly it's not working the error explicitly say `Untrusted Host`

```text
[Mon Sep 12 16:12:27.304795 2022] [php:notice] [pid 63] [client 10.250.2.53:34076] [2022-09-12 14:12:27] request.ERROR: Uncaught PHP Exception Symfony\\Co │
│ mponent\\HttpKernel\\Exception\\BadRequestHttpException: "Untrusted Host "193.148.166.138"." at /opt/kimai/vendor/symfony/http-kernel/HttpKernel.php line  │
│ 83 {"exception":"[object] (Symfony\\\\Component\\\\HttpKernel\\\\Exception\\\\BadRequestHttpException(code: 0): Untrusted Host \\"193.148.166.138\\". at / │
│ opt/kimai/vendor/symfony/http-kernel/HttpKernel.php:83, Symfony\\\\Component\\\\HttpFoundation\\\\Exception\\\\SuspiciousOperationException(code: 0): Untr │
│ usted Host \\"193.148.166.138\\". at /opt/kimai/vendor/symfony/http-foundation/Request.php:1197)"} []                                                      │
│ localhost:8001 10.250.2.53 - - [12/Sep/2022:16:12:27 +0200] "GET /en_GB/login HTTP/1.1" 400 649 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Apple │
│ WebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15"
```

**Comment by robjuz** [comment]
As far as I can see there is now easy way to pass the load balancer IP address to the pod. 

Do you think it would be a bad Idea to set the TRUSTED_HOSTS="*"

Your solution need to "deploy the app twice" because you need to know the IP of the load balancer.

**Comment by robjuz** [comment]
@BackInBash could you please try to set the TRUSTED_HOSTS variable to `127.0.0.1,REMOTE_ADDR` ?

**Pull request closed without merging**
