### PR TITLE
Fix Nominatim download URLs

### PR DESCRIPTION
**Pull request by david-mart**
- Update Nominatim SQL file download URLs for wikimedia importance data, US and GB postcodes.

Based on [this](https://github.com/mediagis/nominatim-docker/commit/3fb113ce2dd20dd0404a5daa5fc3bce05aeaf54c) and [this](https://github.com/mediagis/nominatim-docker/commit/78ad0ba380c68b242bc3ee66e102cf12ec2d1bd5) commits from the official their dockerfile repo

### CODE REVIEW

**Comment by robjuz** [comment]
@david-mart Thank you very much for the PR. Could you please bump the Chart version so I can merge this directly?

**Comment by david-mart** [comment]
Done

**Comment by david-mart** [comment]
Another update - Nominatim API seems to be broken with 4.0 tag. Reverting to 3.7 seems to work fine, with the wiki importance working fine.

**Comment by robjuz** [comment]
Ok. I will merge this like this and will take a look into the 4.0 version. I also provide a postgresql image with nominatim extension that must be updated.

**Pull request merged**
