### PR TITLE
cleanup name, links and dbtest comment

### PR DESCRIPTION
**Pull request by kevinpapst**
You fixed the dbtest.php issue
I renamed Kimai2 to Kimai everywhere, so we have it fixed here as well.
The tobybatch repo is not used anymore.

### CODE REVIEW

**Comment by robjuz** [comment]
@kevinpapst can you please bump the chart version to 4.2.2 so I can merge this directly...

**Comment by kevinpapst** [comment]
What does that mean / why? 
I only updated the README, not the chart itself

**Comment by kevinpapst** [comment]
You talk about this one: https://github.com/robjuz/helm-charts/blob/master/charts/kimai2/Chart.yaml#L5 ?
I just released 2.19 - seems a new version is required anyway 😁 
Do you purposely target a specific version instead of `apache-latest`?

**Comment by robjuz** [comment]
Yes, it's on purpose. I will release a new version.

**Pull request merged**
